Create README.md
MurilloIDM/cea-app pull request #46
Opened 2022-06-18 21:27 UTC by CrisKoch

2022-06-19 02:12 UTC, Gustavo780904 approved these changes
#Uma aplicação para dispositivos móveis que tem como principais objetivos:
sugestão:
"O App CEA é uma aplicação para dispositivos móveis, que tem como principais objetivos:"

2022-06-19 19:10 UTC, MurilloIDM requested changes

2022-06-19 19:23 UTC, CrisKoch commented on README.md
> +Comunidade Entendendo a Adolescência </h1>
ok!

2022-06-19 19:24 UTC, CrisKoch commented on README.md
> +- :floppy_disk: [Back-End](https://github.com/MurilloIDM/cea-back-end)
feito

2022-06-19 19:24 UTC, CrisKoch commented on README.md
> +- :iphone: [Mobile](https://github.com/MurilloIDM/cea-app)
feito!

2022-06-19 19:24 UTC, CrisKoch commented on README.md
> +
alterado!

2022-06-19 21:50 UTC, MurilloIDM approved these changes

2022-06-20 11:57 UTC, tcgontijo approved these changes

2022-06-20 14:39 UTC, merged